-- EdgeTwin AI — H2 Schema (H2 2.x native syntax)

CREATE TABLE IF NOT EXISTS machines (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100) NOT NULL,
    location  VARCHAR(255),
    status    VARCHAR(20)  NOT NULL DEFAULT 'RUNNING'
);

CREATE TABLE IF NOT EXISTS predictions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id          BIGINT NOT NULL REFERENCES machines(id),
    temperature         DOUBLE PRECISION,
    vibration           DOUBLE PRECISION,
    pressure            DOUBLE PRECISION,
    rpm                 DOUBLE PRECISION,
    failure_probability DOUBLE PRECISION NOT NULL,
    health_score        DOUBLE PRECISION NOT NULL,
    risk_level          VARCHAR(20)  NOT NULL,
    recommendation      VARCHAR(500),
    predicted_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pred_machine ON predictions(machine_id);
CREATE INDEX IF NOT EXISTS idx_pred_time    ON predictions(predicted_at DESC);

CREATE TABLE IF NOT EXISTS alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id   BIGINT NOT NULL REFERENCES machines(id),
    severity     VARCHAR(20)  NOT NULL,
    message      VARCHAR(500),
    triggered_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_machine  ON alerts(machine_id);
CREATE INDEX IF NOT EXISTS idx_alert_severity ON alerts(severity);
